name: Convert README to HTML

on:
  push:
    branches:
      - main  # adjust the branch name as needed

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install markdown-to-html
      run: npm install -g markdown-to-html

    - name: Convert README.md to HTML
      run: markdown-to-html README.md > README.html

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add README.html
        git commit -m "Convert README.md to HTML"
        git push
